# Generated by Django 3.2.5 on 2021-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price_range', models.IntegerField(choices=[(28, '0-1500'), (30, '1501-1750'), (33, '1751-2000')])),
            ],
        ),
    ]
